# Generated by Django 5.1 on 2024-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
