# Generated by Django 5.1 on 2024-08-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='properties.property')),
            ],
        ),
    ]
